# Generated by Django 5.2.8 on 2025-12-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('governance', 'Governance'), ('student_affairs', 'Student Affairs'), ('health_safety', 'Health & Safety'), ('it', 'Information Technology'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('document', models.FileField(blank=True, help_text='PDF or Word document', upload_to='policies/documents/')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'University Policy',
                'verbose_name_plural': 'University Policies',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='StrategicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('year', models.IntegerField()),
                ('duration_years', models.IntegerField(default=5, help_text='Duration of strategic plan in years')),
                ('description', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('strategic_goals', models.TextField(blank=True, help_text='Key objectives and goals')),
                ('document', models.FileField(blank=True, help_text='PDF or Word document', upload_to='policies/strategic_plans/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Strategic Plan',
                'verbose_name_plural': 'Strategic Plans',
                'ordering': ['-year'],
                'unique_together': {('year', 'slug')},
            },
        ),
    ]
