# Generated by Django 5.2.8 on 2025-12-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='photo',
            field=models.ImageField(default=0.044000000000000004, help_text='Featured image for news post', upload_to='news_photos/'),
            preserve_default=False,
        ),
    ]
