# Generated by Django 5.2.8 on 2025-12-02 14:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('total_requests', models.IntegerField(default=0)),
                ('completed_requests', models.IntegerField(default=0)),
                ('average_completion_time_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emergency_requests', models.IntegerField(default=0)),
                ('scheduled_maintenance_completed', models.IntegerField(default=0)),
                ('total_maintenance_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_labor_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('downtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('asset_availability_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('repeat_maintenance_issues', models.IntegerField(default=0, help_text='Same asset maintained multiple times')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maintenance Metrics',
                'verbose_name_plural': 'Maintenance Metrics',
                'ordering': ['-month'],
                'unique_together': {('month',)},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('location_description', models.CharField(help_text='Location if not asset-specific', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed description of issue/problem')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent - 24 hours'), ('high', 'High - 3 days'), ('medium', 'Medium - 1 week'), ('low', 'Low - As available')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Staff notes/additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, help_text='Asset needing maintenance', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Request',
                'verbose_name_plural': 'Maintenance Requests',
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_headed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Maintenance Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-annual', 'Semi-annual'), ('annual', 'Annual'), ('bi-annual', 'Bi-annual'), ('as_needed', 'As Needed')], max_length=20)),
                ('last_performed', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('estimated_duration_hours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='assets.asset')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenanceteam')),
            ],
            options={
                'verbose_name': 'Maintenance Schedule',
                'verbose_name_plural': 'Maintenance Schedules',
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_start_time', models.TimeField()),
                ('scheduled_end_time', models.TimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('work_description', models.TextField(blank=True, help_text='Detailed work to be performed')),
                ('materials_required', models.TextField(blank=True, help_text='List of materials/parts needed')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='maintenance.maintenancerequest')),
                ('supervisor', models.ForeignKey(blank=True, help_text='Supervising staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_work_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Work Order',
                'verbose_name_plural': 'Maintenance Work Orders',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('work_performed', models.TextField(help_text='Detailed description of work completed')),
                ('materials_used', models.TextField(blank=True, help_text='Materials/parts actually used')),
                ('parts_replaced', models.TextField(blank=True, help_text='List of replaced parts with part numbers')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parts_cost', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('asset_condition_after', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or recommendations')),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_completions', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_record', to='maintenance.maintenanceworkorder')),
            ],
            options={
                'verbose_name': 'Maintenance Completion',
                'verbose_name_plural': 'Maintenance Completions',
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC/Cooling'), ('it', 'IT/Computing'), ('mechanical', 'Mechanical'), ('civil', 'Civil/Building'), ('general', 'General Maintenance'), ('laboratory', 'Laboratory Equipment'), ('other', 'Other')], default='general', max_length=20)),
                ('license_number', models.CharField(blank=True, help_text='Professional license/certification', max_length=50)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians', to='maintenance.maintenanceteam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Technicians',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.technician'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='maintenance.technician'),
        ),
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('work_description', models.TextField()),
                ('supervisor', models.CharField(blank=True, max_length=255)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('spare_parts_used', models.TextField(blank=True)),
                ('asset_condition_before', models.CharField(blank=True, max_length=50)),
                ('asset_condition_after', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_history', to='assets.asset')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenanceworkorder')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.technician')),
            ],
            options={
                'verbose_name': 'Maintenance History',
                'verbose_name_plural': 'Maintenance Histories',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_type', models.CharField(choices=[('technician_start', 'Technician - Work Start'), ('technician_end', 'Technician - Work Completion'), ('receiver_acceptance', 'Receiver - Work Acceptance'), ('supervisor_approval', 'Supervisor - Approval'), ('quality_check', 'QA Inspector - Quality Check')], max_length=25)),
                ('signature_data', models.TextField(help_text='Base64 encoded digital signature image')),
                ('signature_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, help_text='Device used for signing', max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_signatures', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='maintenance.maintenanceworkorder')),
            ],
            options={
                'verbose_name': 'Maintenance Signature',
                'verbose_name_plural': 'Maintenance Signatures',
                'ordering': ['-signature_timestamp'],
                'unique_together': {('work_order', 'signature_type')},
            },
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['status'], name='maintenance_status_0773c2_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['priority'], name='maintenance_priorit_ec7e12_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['assigned_to'], name='maintenance_assigne_979040_idx'),
        ),
    ]
