# Generated by Django 5.2.8 on 2025-12-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default=0.0010864197530864198, help_text='Event banner image', upload_to='event_photos/'),
            preserve_default=False,
        ),
    ]
